[workspace]
resolver = "2"
members = ["crates/staticsmith-core", "crates/staticsmith-deploy", "src-tauri"]

[workspace.package]
version = "2.0.0"
edition = "2021"
rust-version = "1.80"
license = "MIT"
repository = "https://github.com/dreamsxin/StaticSmith"
authors = ["dreamszhu <dreamsxin@qq.com>"]

[workspace.dependencies]
staticsmith-core = { path = "crates/staticsmith-core" }
staticsmith-deploy = { path = "crates/staticsmith-deploy" }

anyhow = "1.0"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
tera = "1.20"
rusqlite = { version = "0.32", features = ["bundled"] }
rayon = "1.10"
walkdir = "2.5"
pulldown-cmark = "0.12"
gray_matter = "0.2"
chrono = { version = "0.4", features = ["serde"] }
sha2 = "0.10"
md-5 = "0.10"
regex = "1.11"
notify = "6.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
slug = "0.1"
base64 = "0.22"
tempfile = "3.12"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
panic = "abort"
